name: Build & Release
on: 
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" amd64 && nmake release
        shell: cmd
